# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "10.1.0"

    steps:
      - checkout
      - run: sudo apt-get clean && sudo apt-get -y update && sudo apt-get install -y locales
      - run: sudo locale-gen en_US.UTF-8
      - run: sudo locale-gen en en_US en_US.UTF-8
      - run: sudo dpkg-reconfigure locales
      - run: sudo gem install fastlane
      - run: fastlane init

      # Build the app and run tests
      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 6
            SCAN_SCHEME: Osiris12JB

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
